#!/usr/bin/env bash
# Idempotent VPS backup bootstrap step: state/ciphertext directories,
# root-only secret files, and the family-app-backup systemd timer/service
# units. Runs ON the target host as root/sudo. Safe to re-run.
#
# Ruling: reuses the shared cluster's EXISTING Postgres superuser
# (POSTGRES_SUPERUSER_PASSWORD, already generated by 30-postgres.sh into
# ${SHARED_PG_DIR}/.env) rather than minting a narrower "backup" role.
# pg_dumpall --globals-only and a pg_dump of every non-template database
# both need superuser-equivalent read access across every app's schema;
# a correctly-scoped read-everywhere role is possible but is a follow-up,
# not required for this plan's scope. Cost if wrong: the backup identity
# can read (but, per Task 1, never upload-replace or read back from GCS)
# every app's data -- the same blast radius `psql` already has today from
# this same host as root.
#
# Required env vars:
#   SHARED_PG_DIR          - e.g. /opt/family-app/postgres (already
#                              bootstrapped by 30-postgres.sh)
#   BACKUP_DIR             - e.g. /opt/family-app/backup
#   BACKUP_GCS_URI         - e.g. gs://expense-tax-tobytran-2026-backups
#   BACKUP_HOST_ID         - stable identifier embedded in object names
#   AGE_RECIPIENT          - public age1... recipient (Task 1 operator keeps the private half)
#   RECEIPT_VOLUME         - name of the app's receipt Docker volume (e.g.
#                              expense-tax-production_expense_tax_production_storage)
#                              -- a named volume, not a host path: Docker can
#                              mount it into the backup container by name
#                              regardless of which Compose project created it
#   BACKUP_WRITER_KEY_JSON - full JSON content of the Task 1 writer service account key
#   BACKUP_IMAGE           - pinned backup image ref (digest, not a mutable tag)
#   UNIT_FILES_DIR         - dir (already scp'd by bootstrap.sh) holding the
#                              three *.service/*.timer template files
set -euo pipefail

: "${SHARED_PG_DIR:?SHARED_PG_DIR is required}"
: "${BACKUP_DIR:?BACKUP_DIR is required}"
: "${BACKUP_GCS_URI:?BACKUP_GCS_URI is required}"
: "${BACKUP_HOST_ID:?BACKUP_HOST_ID is required}"
: "${AGE_RECIPIENT:?AGE_RECIPIENT is required}"
: "${RECEIPT_VOLUME:?RECEIPT_VOLUME is required}"
: "${BACKUP_WRITER_KEY_JSON:?BACKUP_WRITER_KEY_JSON is required}"
: "${BACKUP_IMAGE:?BACKUP_IMAGE is required}"
: "${UNIT_FILES_DIR:?UNIT_FILES_DIR is required}"

[[ -f "${SHARED_PG_DIR}/.env" ]] || {
  echo "[backup] ERROR: ${SHARED_PG_DIR}/.env not found -- run the postgres step first" >&2
  exit 1
}
pg_superuser_password="$(grep -E '^POSTGRES_SUPERUSER_PASSWORD=' "${SHARED_PG_DIR}/.env" | tail -1 | cut -d= -f2-)"
[[ -n "$pg_superuser_password" ]] || {
  echo "[backup] ERROR: POSTGRES_SUPERUSER_PASSWORD not found in ${SHARED_PG_DIR}/.env" >&2
  exit 1
}

echo "[backup] ensuring state/ciphertext directories"
mkdir -p "${BACKUP_DIR}/state" "${BACKUP_DIR}/ciphertext"
chmod 0700 "${BACKUP_DIR}/state" "${BACKUP_DIR}/ciphertext"
chown root:root "${BACKUP_DIR}/state" "${BACKUP_DIR}/ciphertext"

mkdir -p /etc/family-app
chmod 0700 /etc/family-app

echo "[backup] writing root-only credential files"
umask 077
printf '%s' "$pg_superuser_password" > /etc/family-app/backup-pgpassword
chmod 0400 /etc/family-app/backup-pgpassword
printf '%s' "$BACKUP_WRITER_KEY_JSON" > /etc/family-app/backup-writer-key.json
chmod 0400 /etc/family-app/backup-writer-key.json

cat > /etc/family-app/backup.env <<ENV
BACKUP_GCS_URI=${BACKUP_GCS_URI}
BACKUP_HOST_ID=${BACKUP_HOST_ID}
AGE_RECIPIENT=${AGE_RECIPIENT}
RECEIPT_STORAGE_DIR=/receipts
BACKUP_STATE_DIR=/state
BACKUP_CIPHERTEXT_DIR=/ciphertext
GOOGLE_APPLICATION_CREDENTIALS=/run/secrets/writer-key.json
PGHOST=postgres
PGPORT=5432
PGUSER=postgres
PGPASSWORD_FILE=/run/secrets/pgpassword
ENV
chmod 0600 /etc/family-app/backup.env

echo "[backup] installing systemd units"
sed -e "s#__BACKUP_IMAGE__#${BACKUP_IMAGE}#g" -e "s#__RECEIPT_VOLUME__#${RECEIPT_VOLUME}#g" \
  "${UNIT_FILES_DIR}/family-app-backup.service" > /etc/systemd/system/family-app-backup.service
sed -e "s#__BACKUP_IMAGE__#${BACKUP_IMAGE}#g" -e "s#__RECEIPT_VOLUME__#${RECEIPT_VOLUME}#g" \
  "${UNIT_FILES_DIR}/family-app-backup-retry.service" > /etc/systemd/system/family-app-backup-retry.service
cp "${UNIT_FILES_DIR}/family-app-backup.timer" /etc/systemd/system/family-app-backup.timer
chmod 0644 /etc/systemd/system/family-app-backup.service /etc/systemd/system/family-app-backup-retry.service /etc/systemd/system/family-app-backup.timer

systemctl daemon-reload
systemctl enable --now family-app-backup.timer

echo "[backup] done: timer active, next run: $(systemctl list-timers family-app-backup.timer --no-legend 2>/dev/null | awk '{print $1, $2, $3}')"
