# generated by datamodel-codegen:
#   filename:  strategy-spec-v1.schema.json

from __future__ import annotations

from typing import Annotated, Literal

from ai_trading.contracts.base import SpecModel
from pydantic import ConfigDict, Field, RootModel


class Alert(SpecModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    channels: Annotated[list[Literal["inbox", "telegram", "slack"]], Field(max_length=3, min_length=1)]
    severity: Literal["info", "opportunity", "risk"] | None = None


class Universe(SpecModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    watchlist: Annotated[str, Field(max_length=80, min_length=1)]


class Symbol(RootModel[str]):
    root: Annotated[str, Field(pattern="^\\/?[A-Z][A-Z0-9.]{0,9}$")]


class Universe1(SpecModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    symbols: Annotated[list[Symbol], Field(max_length=70, min_length=1)]


class Watch(SpecModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    runOn: Literal["bar_close_1m", "premarket_0830", "daily_close", "weekly"]
    session: Literal["regular", "extended"]
    universe: Universe | Universe1


class LevelOperand1(SpecModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    level: Literal["prior_day_high", "prior_day_low", "prior_day_close", "premarket_high", "premarket_low", "overnight_high", "overnight_low"]


class LevelOperand2(SpecModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    level: Literal["opening_range_high", "opening_range_low"]
    minutes: Annotated[int, Field(ge=1, le=120)]


class LevelOperand3(SpecModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    days: Annotated[int, Field(ge=2, le=260)]
    level: Literal["n_day_high", "n_day_low"]


class Limits(SpecModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    cooldownMinutes: Annotated[int | None, Field(ge=0, le=1440)] = None
    flatBy: Annotated[str | None, Field(pattern="^([01][0-9]|2[0-3]):[0-5][0-9]$")] = None
    maxOpenPositions: Annotated[int | None, Field(ge=1, le=10)] = None
    maxPositionUsd: Annotated[float | None, Field(gt=0.0, le=1000000.0)] = None
    maxTradesPerDay: Annotated[int | None, Field(ge=1, le=12)] = None
    pauseAfterDailyLossUsd: Annotated[float | None, Field(gt=0.0, le=1000000.0)] = None


class Size(SpecModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    riskUsd: Annotated[float, Field(gt=0.0, le=100000.0)]


class Size1(SpecModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    shares: Annotated[int, Field(ge=1, le=100000)]


class Size2(SpecModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    pctOfBook: Annotated[float, Field(gt=0.0, le=100.0)]


class Size3(SpecModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    contracts: Annotated[int, Field(ge=1, le=100)]


class Stop(SpecModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    atrMultiple: Annotated[float, Field(gt=0.0, le=20.0)]


class Target(SpecModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    r: Annotated[float, Field(gt=0.0, le=20.0)]


class PaperOrder(SpecModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    side: Literal["buy", "sell"]
    size: Size | Size1 | Size2 | Size3
    stop: Stop | LevelOperand1 | LevelOperand2 | LevelOperand3
    target: Target | LevelOperand1 | LevelOperand2 | LevelOperand3


class SeriesOperand1(SpecModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    series: Literal["open", "high", "low", "close", "volume", "vwap", "gap_pct"]


class SeriesOperand2(SpecModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    length: Annotated[int, Field(ge=2, le=500)]
    series: Literal["sma", "ema", "rsi", "atr"]


class SeriesOperand3(SpecModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    lookbackDays: Annotated[int, Field(ge=1, le=60)]
    series: Literal["rvol"]


class TimeBetweenCondition(SpecModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    end: Annotated[str, Field(pattern="^([01][0-9]|2[0-3]):[0-5][0-9]$")]
    op: Literal["time_between"]
    start: Annotated[str, Field(pattern="^([01][0-9]|2[0-3]):[0-5][0-9]$")]


class ValueOperand(SpecModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    value: float


class Then(SpecModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    alert: Alert
    paperOrder: PaperOrder | None = None


class WithinPctCondition(SpecModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    left: ValueOperand | SeriesOperand1 | SeriesOperand2 | SeriesOperand3 | LevelOperand1 | LevelOperand2 | LevelOperand3
    op: Literal["within_pct"]
    pct: Annotated[float, Field(gt=0.0, le=100.0)]
    right: ValueOperand | SeriesOperand1 | SeriesOperand2 | SeriesOperand3 | LevelOperand1 | LevelOperand2 | LevelOperand3


class CompareCondition(SpecModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    left: ValueOperand | SeriesOperand1 | SeriesOperand2 | SeriesOperand3 | LevelOperand1 | LevelOperand2 | LevelOperand3
    op: Literal["gt", "gte", "lt", "lte", "crosses_above", "crosses_below"]
    right: ValueOperand | SeriesOperand1 | SeriesOperand2 | SeriesOperand3 | LevelOperand1 | LevelOperand2 | LevelOperand3


class StrategySpecV1(SpecModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    limits: Limits | None = None
    name: Annotated[str, Field(max_length=80, min_length=1)]
    schemaVersion: Literal[1]
    then: Then
    watch: Watch
    when: CompareCondition | WithinPctCondition | TimeBetweenCondition | AllCondition | AnyCondition | NotCondition


class AllCondition(SpecModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    all: Annotated[
        list[CompareCondition | WithinPctCondition | TimeBetweenCondition | AllCondition | AnyCondition | NotCondition],
        Field(max_length=20, min_length=1),
    ]


class AnyCondition(SpecModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    any: Annotated[
        list[CompareCondition | WithinPctCondition | TimeBetweenCondition | AllCondition | AnyCondition | NotCondition],
        Field(max_length=20, min_length=1),
    ]


class NotCondition(SpecModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    not_: Annotated[
        CompareCondition | WithinPctCondition | TimeBetweenCondition | AllCondition | AnyCondition | NotCondition,
        Field(alias="not"),
    ]


StrategySpecV1.model_rebuild()
AllCondition.model_rebuild()
AnyCondition.model_rebuild()
NotCondition.model_rebuild()
