packages:
  - 'frontend/*'
  - 'services/*'
  - 'packages/*'
allowBuilds:
  '@swc/core': true
  esbuild: true
  protobufjs: false
  unrs-resolver: true
minimumReleaseAgeExclude:
  - googleapis@183.0.0
